modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="cbgirl"
version="0.0.0.2"
displayName="Cutie Bootie"
displayURL="https://quimsoggybum.github.io/cutiebootie.html"
logoFile="logo.png"
credits="All ABDL and diaper lovers, enjoy our cute diapers"
authors="QuimSoggyBum"
description="This is a Add-on for NappyCraft, We add ABDL related diapers"

# Start of user code block mod configuration
# End of user code block mod configuration


# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.cbgirl]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.cbgirl]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration